Algoritmo "CalculoAreaquadrado"
// Disciplina   : [Programação e Algoritmos]
// Professora   : Cintia Pinho
// Descrição   : Esse programa calcula a area do quadrado
// Autor(a)    : Vivian Matsuoka
// Data atual  : 11/03/2021
Var
//Declarações de variáveis

lado, area: real

Inicio
//entrada
escreva("digite o lado do quadrado: ")
leia (lado)

//processamento
area <- lado*lado

//saida
escreva("a area do quadrado é: ", area,"m2")

Fimalgoritmo