Algoritmo "ativ10"
// Disciplina   : Programação e Algoritmos
// Professor   : Cintia Pinho
// Autor(a)    : Vivian Matsuoka
// Data atual  : 24/08/2021


Var

fatorial, x, num:inteiro

Inicio

escreval ("Digite um número: ")
leia (num)

x <- 1
fatorial <- 1

enquanto x <= num faca
  fatorial <- fatorial * x
  x <- x +1
fimenquanto

escreval ("Seu fatorial é: ",fatorial)
Fimalgoritmo