Algoritmo "competirse"
// Disciplina   : Programação e algoritmos
// Professor   : Cintia Pinho
// Autor(a)    : Vivian Matsuoka
// Data atual  : 18/06/2021

Var
idade, altura:real

Inicio
escreval ("Digite sua idade: ")
leia(idade)
escreval ("Digite sua altura: ")
leia(altura)

se (idade>=18) e (altura>=1.75) entao

   escreval ("Tudo certo, você poderá competir.")

senao

     escreval ("Infelizmente você não poderá competir.")

fimse

fimalgoritmo